schema: draft-07
name: openai-chat
description: OpenAI simple chat bot example.
source_url: github.com/massdriver-cloud/application-examples/tree/main/openai-chat
access: private
type: application

app:
  # Use jq expressions to build environment variables from input params or connections
  envs:
    LOG_LEVEL: .params.log_level
    PORT: .params.port | tostring
    HOST: .params.ingress.host
  policies: []
  secrets:
    OPENAI_API_KEY:
      required: true # if a secret is required, massdriver will block deployments that are missing this secret
      title: "OpenAI API Key"
      description: "A great description for the UI"

params:
  properties:
    resourceRequests:
      type: object
      required:
        - cpu
        - memory
      properties:
        cpu:
          title: CPU Cores
          description: The expected CPU cores required for this application. Fractional numbers are allowed (0.5 is one half of a CPU core).
          type: number
          minimum: 0.001
        memory:
          title: Memory
          description: The expected Memory resources required for this application.
          type: number
    replicas:
      title: Replicas
      description: Manage the number of concurrent replicas of your application
      type: object
      properties:
        autoscalingEnabled:
          title: Enable Horizontal Pod Autoscaling
          description: A Horizontal Pod Autoscaler will enable your application to automatically add or remove replicas based on resource utilization.
          type: boolean
          default: false
      dependencies:
        autoscalingEnabled:
          oneOf:
            - properties:
                autoscalingEnabled:
                  const: false
                replicaCount:
                  title: Number of Replicas
                  description: Fixed number of replicas to constantly maintain
                  type: integer
                  minimum: 1
                  default: 1
              required:
                - replicaCount
            - properties:
                autoscalingEnabled:
                  const: true
                minReplicas:
                  title: Minimum Replicas
                  description: Minimum number of replicas the autoscaler will maintain, based on target resource utilization
                  type: integer
                  minimum: 1
                  default: 1
                maxReplicas:
                  title: Maximum Replicas
                  description: Maximum number of replicas the autoscaler will provision, based on target resource utilization
                  type: integer
                  minimum: 1
                  default: 10
                targetCPUUtilizationPercentage:
                  title: Target CPU Utilization Percentage
                  description: The percentage of allocated CPU resources the autoscaler should target, based on the values specified in the 'Resources' section. If utilization rises sufficiently above this percentage, replicas will be added. If utilization drops sufficiently below this percentage, replicas will be removed.
                  type: integer
                  minimum: 1
                  default: 80
              required:
                - minReplicas
                - maxReplicas
                - targetCPUUtilizationPercentage
    ingress:
      title: Ingress
      description: Configure the application for public internet accessibility
      type: object
      properties:
        enabled:
          title: Enable Public Internet Access
          type: boolean
      dependencies:
        enabled:
          oneOf:
            - properties:
                enabled:
                  const: false
            - properties:
                enabled:
                  const: true
                host:
                  title: HTTP Hostname
                  description: The hostname which this application should be accessable on, such as www.example.com. You must own this domain and have it associated with this kubernetes cluster if you would like automatic DNS record and SSL certificate management.
                  type: string
                  pattern: ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
                  message:
                    pattern: Hostname should consist of letters, numbers, periods and hyphens, such as www.example.com
                path:
                  title: HTTP Path
                  description: The HTTP path which, when appended to the host above, this application will serve traffic on
                  type: string
                  default: "/"
                  pattern: ^\/.*$
                  message:
                    pattern: Must begin with a '/' and be a valid HTTP endpoint
              required:
                - host
                - path

connections:
  required:
    - kubernetes_cluster
  properties:
    kubernetes_cluster:
      $ref: massdriver/kubernetes-cluster
    aws_authentication:
      $ref: massdriver/aws-iam-role
    gcp_authentication:
      $ref: massdriver/gcp-service-account
    azure_authentication:
      $ref: massdriver/azure-service-principal

ui:
  ## If you need to allow an end user to select the container repository at deploy time, our smart widget can be used.
  ## Additional documentation here: https://docs.massdriver.cloud/bundles/custom-widgets-and-fields
  # image:
  #   repository:
  #     ui:field: "containerRepositoriesDropdown"
  #     cloud: "aws"
  ui:order:
    - resourceRequests
    - replicas
    - port
    - ingress
    - "*"
  resourceRequests:
    memory:
      ui:field: conversionFieldData
      unit: Bytes
  replicas:
    items:
      ui:order:
        - autoscalingEnabled
        - replicaCount
        - minReplicas
        - maxReplicas
        - targetCPUUtilizationPercentage
  ingress:
    items:
      ui:order:
        - enabled
        - host
        - path
