version: "3"

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SUBSCRIPTION_ID=projects/GCP_PROJECT/subscriptions/GCP_SUBSCRIPTION
      - GOOGLE_APPLICATION_CREDENTIALS=creds.json
    volumes:
      - ./creds.json:/creds.json

