version: "3"

volumes:
  module_cache:

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:4000
    environment:
      - AZURE_STORAGE_ACCOUNT_NAME=beebeazdevassetst92p
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=beebeazdevassetst92p;AccountKey=+97WZvgQs9rfWQEJhBlnLXunXsXZJYt3gGt+ev6q2AYSFmkxBn8nxtcU7IE37vMILDBJQqlyCRtb+AStftrq5A==;EndpointSuffix=core.windows.net
    volumes:
      - module_cache:/node_modules
