version: "3"

services:
  mongo:
    image: mongo:4
    # volumes:
    #   - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    build:
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
    ports:
      - "3000:3000"
    depends_on:
      - mongo
