version: "3"

services:
  app_dev:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 4000:4000
    environment:
      # - BACKENDS=https://aks-app-000.mdazuresbx.com/,https://app-service-001.mdazuresbx.com/,https://function-app-003.mdazuresbx.com/,https://vm-000.mdazuresbx.com/
      - BACKEND0=https://aks-app-000.mdazuresbx.com/

  app_release:
    platform: linux/amd64
    build:
      dockerfile: ./Dockerfile
      context: .
