version: "3"

services:
  model_server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    ports:
      - 6000:5000
