version: "3"

services:
  app_dev:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 4000:4000
    environment:
      - ENDPOINT=${ENDPOINT}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
      - RECIPIENT_NAME=${RECIPIENT_NAME}

  app_release:
    platform: linux/amd64
    build:
      dockerfile: ./Dockerfile
      context: .