FROM rust:latest as builder

RUN echo "fn main() {}" > placeholder.rs
COPY Cargo.toml .
RUN sed -i 's#src/main.rs#placeholder.rs#' Cargo.toml
RUN cargo build
RUN sed -i 's#placeholder.rs#src/main.rs#' Cargo.toml
COPY . .
RUN cargo build --release

FROM debian:11-slim
# If you need any runtime dependencies...
# RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /target/release/app /usr/local/bin/app
CMD ["app"]
