version: "3"

services:
  app_dev:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      - PORT=4000
    ports:
      - 3000:4000

  app_release:
    # TODO: build on arm, compile to x86
    platform: linux/amd64
    build:
      dockerfile: ./Dockerfile.release
      context: .
    ports:
      - 3000:3000
