image:
  repository: registry.hub.docker.com/massdrivercloud/bloby
  tag:

command: []
args: []

envs: []
port: 80

serviceAccount:
  annotations: {}
  labels: {}
  name:

resourceRequests: {}
resourceLimits: {}

replicas:
  autoscalingEnabled: false
  replicaCount:
  minReplicas:
  maxReplicas:
  targetCPUUtilizationPercentage:

ingress:
  annotations: {}
  enabled: true
  className:
  host:
  path:

commonLabels: {}

pod:
  annotations: {}
