image:
  repository: us-west2-docker.pkg.dev/mdc-trellis-staging-trellis/trellis/k8s-pubsub-worker
  tag: 1

command: []
args: []

envs: []
port:

serviceAccount:
  annotations: {}
  name:

resourceRequests: {}
resourceLimits: {}

replicas:
  autoscalingEnabled: false
  replicaCount:
  minReplicas:
  maxReplicas:
  targetCPUUtilizationPercentage:

ingress:
  annotations: {}
  enabled: true
  className:
  host:
  path:

commonLabels: {}

pod:
  annotations: {}
