version: "3"

services:
  app_dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:80
    environment:
      - COGNITIVE_SERVICES_ENDPOINT=https://unique12345.cognitiveservices.azure.com/

  app_release:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
