
dev.local:
	PGUSER=some_user \
	PGPASSWORD=some_password \
  PGDATABASE=some_database \
  PGPORT=5432 \
	PGHOST=localhost \
	mix phx.server

dev.migrate:
	PGUSER=some_user \
	PGPASSWORD=some_password \
  PGDATABASE=some_database \
  PGPORT=5432 \
	PGHOST=localhost \
	mix ecto.migrate
