namespace: default
image:
  repository:
  tag:

nameOverride: thing

command: []
args: []

envs: []
port:

serviceAccount:
  annotations: {}
  name:

resourceRequests: {
  cpu: 100m,
  memory: 128Mi
}
resourceLimits: {
  cpu: 100m,
  memory: 128Mi
}

replicaCount:
autoscaling:
  enabled: false
  minReplicas:
  maxReplicas:
  targetCPUUtilizationPercentage:

ingress:
  annotations: {}
  enabled: true
  className:
  host:
  path:

labels: {}

# nodeSelector: {}

# tolerations: []

# affinity: {}
