# https://betterprogramming.pub/rails-6-development-with-docker-55437314a1ad
version: "3"

volumes:
  db_data_v:
  gem_cache:
  shared_data_v:

services:
  app:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASS: example
      RAILS_ENV: development
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    # command: ['rails', 'db:create']
    ports:
      - "3000:3000"
    volumes:
      - .:/var/app
      - shared_data_v:/var/shared
      - gem_cache:/usr/local/bundle/gems
    depends_on:
      - database
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - db_data_v:/var/lib/postgresql/data
      - shared_data_v:/var/shared
    ports:
      - "5432:5432"

