name: Push Docker Image to Azure Container Registry
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to the Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        flavor: |
          latest=true
        images: ${{ secrets.ACR_LOGIN_SERVER }}/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=sha
    - name: Build and push
      id: docker-build
      uses: docker/build-push-action@v2
      with:
        file: k8s-express-mongo/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}

